language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
    - node_modules
services: mongodb
before_install:
  - npm install -g npm@latest
install:
  - npm install -g codecov
script:
  - npm run coverage
  - codecov
