language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
services: mongodb
before_install:
  - npm install -g npm@6.1.0
install:
  - npm install -g codecov
script:
  - npm run coverage
  - codecov
