language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=test
services: mongodb
before_install:
  - node --version
  - rm -rf ./node_modules package-lock.json
  - npm install -g npm@6.1.0
  # - npm uninstall -D husky lint-staged
install:
  - npm install -g codecov
script:
  - npm run coverage
  - codecov
